const text={
 ko:{title:'계정 및 데이터 삭제',intro:'앱을 사용할 수 있다면 메뉴의 “계정 및 데이터 삭제”를 이용하세요. 앱을 사용할 수 없다면 미리 보관한 계정 ID와 비밀 삭제 코드로 아래에서 삭제할 수 있습니다.',uid:'계정 ID',code:'비밀 삭제 코드',warning:'계정·닉네임·포인트·배지 및 관련 신고 데이터를 삭제합니다. 되돌릴 수 없습니다. 기기 안의 학습 기록은 원격으로 삭제할 수 없습니다.',confirm:'삭제 대상이 제 계정이며 영구 삭제에 동의합니다.',submit:'계정 및 데이터 삭제',noCode:'코드가 없으면 닉네임만으로 삭제할 수 없습니다. 앱에서 코드를 발급하거나 이메일로 문의하세요. 삭제 코드를 이메일로 보내지 마세요.',retention:'요청을 검증하면 삭제를 진행합니다. 중간에 실패하면 같은 ID와 코드로 다시 시도하세요. 재시도 확인용 해시 기록은 7일 후 정리 대상이 되며, 외부 서비스 기술 로그에는 제공자의 보관 정책이 적용될 수 있습니다.',privacy:'개인정보처리방침',ready:'준비되었습니다.',busy:'삭제 중입니다. 창을 닫지 말아 주세요.',done:'계정과 서버 데이터를 삭제했습니다. 기기 안의 기록은 기기에서 별도로 지워 주세요.',invalid:'계정 ID 또는 코드가 올바르지 않습니다. 코드를 다시 발급했다면 최신 코드를 사용하세요.',error:'삭제를 완료하지 못했습니다. ID와 코드를 보관하고 같은 정보로 다시 시도해 주세요.',limit:'요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.',unavailable:'서버 연결을 준비하지 못했습니다. 연결을 확인하거나 운영자에게 문의하세요.'},
 en:{title:'Delete account and data',intro:'If you can use the app, choose “Delete account & data” in its menu. Otherwise, use the account ID and secret deletion code you saved earlier.',uid:'Account ID',code:'Secret deletion code',warning:'This permanently deletes your account, nickname, points, badge and related reports. It cannot be undone. Learning records on your device cannot be erased remotely.',confirm:'This is my account and I agree to permanent deletion.',submit:'Delete account and data',noCode:'A nickname alone cannot verify deletion. Issue a code in the app or contact us by email for assistance. Do not email your deletion code.',retention:'Deletion begins after verification. If interrupted, retry with the same ID and code. Hashed retry receipts become eligible for cleanup after 7 days; provider technical logs may follow the provider’s retention policy.',privacy:'Privacy Policy',ready:'Ready.',busy:'Deleting. Please keep this page open.',done:'Account and server data deleted. Remove local learning records on your device separately.',invalid:'The account ID or code is invalid. If you replaced your code, use the newest one.',error:'Deletion could not be completed. Keep the ID and code and retry with the same details.',limit:'Too many requests. Please try again later.',unavailable:'Could not prepare the server connection. Check your connection or contact the operator.'},
 es:{title:'Eliminar cuenta y datos',intro:'Si puedes usar la app, elige “Eliminar cuenta y datos” en el menú. Si no, utiliza el ID de cuenta y el código secreto de eliminación que guardaste.',uid:'ID de la cuenta',code:'Código secreto de eliminación',warning:'Se eliminan de forma permanente la cuenta, el apodo, los puntos, la insignia y las denuncias relacionadas. No se puede deshacer. Los registros del dispositivo no pueden borrarse a distancia.',confirm:'Esta es mi cuenta y acepto su eliminación permanente.',submit:'Eliminar cuenta y datos',noCode:'El apodo no basta para verificar la eliminación. Genera un código en la app o contacta por correo para obtener ayuda. No envíes tu código por correo.',retention:'La eliminación comienza tras verificar la solicitud. Si se interrumpe, vuelve a intentarlo con el mismo ID y código. Los registros hash para reintentos se pueden eliminar después de 7 días; los registros técnicos del proveedor pueden seguir su política de conservación.',privacy:'Política de privacidad',ready:'Listo.',busy:'Eliminando. Mantén esta página abierta.',done:'Se eliminaron la cuenta y los datos del servidor. Borra por separado los registros locales del dispositivo.',invalid:'El ID o el código no son válidos. Si reemplazaste el código, utiliza el más reciente.',error:'No se pudo completar la eliminación. Conserva el ID y el código y vuelve a intentarlo con los mismos datos.',limit:'Demasiadas solicitudes. Inténtalo más tarde.',unavailable:'No se pudo preparar la conexión. Comprueba la conexión o contacta con el operador.'}
};
let lang=['ko','en','es'].includes(navigator.language.slice(0,2))?navigator.language.slice(0,2):'en',busy=false,call;
const $=id=>document.getElementById(id);
function render(){document.documentElement.lang=lang;const t=text[lang];for(const [id,key] of Object.entries({'title':'title','intro':'intro','uid-label':'uid','code-label':'code','warning':'warning','confirm-label':'confirm','submit':'submit','no-code':'noCode','retention':'retention','privacy-link':'privacy'}))$(id).textContent=t[key];$('status').textContent=busy?t.busy:call?t.ready:t.unavailable;}
document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{if(!busy){lang=b.dataset.lang;render()}});render();
try{const [{functions},{httpsCallable}]=await Promise.all([import('./firebase-client.js'),import('https://www.gstatic.com/firebasejs/12.2.1/firebase-functions.js')]);call=httpsCallable(functions,'safetyDeleteAccount',{timeout:300000});$('submit').disabled=false;render()}catch{$('status').textContent=text[lang].unavailable}
$('delete-form').addEventListener('submit',async e=>{e.preventDefault();if(busy||!call)return;busy=true;$('submit').disabled=true;render();let success=false;
 try{await call({uid:$('uid').value.trim(),code:$('code').value.trim()});success=true;$('code').value='';$('uid').value='';$('confirm').checked=false;$('status').textContent=text[lang].done}
 catch(e){const code=String(e.code||'');$('status').textContent=code.includes('permission-denied')?text[lang].invalid:code.includes('resource-exhausted')?text[lang].limit:text[lang].error}
 finally{busy=false;$('submit').disabled=success}
});
// No localStorage, query parameters, analytics or console logging of deletion secrets.
